apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nats-helper.fullname" . }}-config
  labels:
    {{- include "nats-helper.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- toYaml .Values.config | nindent 4 }}